
import { useState, useEffect } from 'react';

const translations = {
  en: {
    app_title: "Smart Resume Builder",
    step_personal: "Personal",
    step_experience: "Experience", 
    step_education: "Education",
    step_skills: "Skills",
    step_preview: "Preview",
    personal_info: "Personal Information",
    full_name: "Full Name",
    professional_title: "Professional Title",
    summary: "Professional Summary",
    email: "Email",
    phone: "Phone",
    linkedin: "LinkedIn",
    website: "Website/Portfolio",
    work_experience: "Work Experience",
    company_name: "Company Name",
    job_title: "Job Title",
    start_date: "Start Date",
    end_date: "End Date",
    current_job: "Current Job",
    job_description: "Job Description",
    add_experience: "+ Add Experience",
    education: "Education",
    school_name: "School/University",
    degree: "Degree",
    education_description: "Description",
    add_education: "+ Add Education",
    skills_languages: "Skills & Languages",
    skills: "Skills",
    skills_placeholder: "Type a skill and press Enter",
    languages_spoken: "Languages Spoken",
    select_proficiency: "Select Proficiency",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    native: "Native",
    add_language: "+ Add Language",
    certifications: "Certifications (Optional)",
    preview_generate: "Preview & Generate",
    choose_template: "Choose Template",
    modern_template: "Modern",
    classic_template: "Classic",
    minimal_template: "Minimal",
    previous: "Previous",
    next: "Next",
    generate_pdf: "Generate PDF",
    remove: "Remove",
    fill_required_fields: "Please fill in all required fields"
  },
  'pt-br': {
    app_title: "Construtor de Currículo Inteligente",
    step_personal: "Pessoal",
    step_experience: "Experiência",
    step_education: "Educação",
    step_skills: "Habilidades",
    step_preview: "Visualizar",
    personal_info: "Informações Pessoais",
    full_name: "Nome Completo",
    professional_title: "Título Profissional",
    summary: "Resumo Profissional",
    email: "E-mail",
    phone: "Telefone",
    linkedin: "LinkedIn",
    website: "Website/Portfólio",
    work_experience: "Experiência Profissional",
    company_name: "Nome da Empresa",
    job_title: "Cargo",
    start_date: "Data de Início",
    end_date: "Data de Término",
    current_job: "Emprego Atual",
    job_description: "Descrição do Cargo",
    add_experience: "+ Adicionar Experiência",
    education: "Educação",
    school_name: "Escola/Universidade",
    degree: "Graduação",
    education_description: "Descrição",
    add_education: "+ Adicionar Educação",
    skills_languages: "Habilidades e Idiomas",
    skills: "Habilidades",
    skills_placeholder: "Digite uma habilidade e pressione Enter",
    languages_spoken: "Idiomas Falados",
    select_proficiency: "Selecionar Proficiência",
    beginner: "Iniciante",
    intermediate: "Intermediário",
    advanced: "Avançado",
    native: "Nativo",
    add_language: "+ Adicionar Idioma",
    certifications: "Certificações (Opcional)",
    preview_generate: "Visualizar e Gerar",
    choose_template: "Escolher Modelo",
    modern_template: "Moderno",
    classic_template: "Clássico",
    minimal_template: "Minimalista",
    previous: "Anterior",
    next: "Próximo",
    generate_pdf: "Gerar PDF",
    remove: "Remover",
    fill_required_fields: "Por favor, preencha todos os campos obrigatórios"
  },
  es: {
    app_title: "Constructor de Currículum Inteligente",
    step_personal: "Personal",
    step_experience: "Experiencia",
    step_education: "Educación",
    step_skills: "Habilidades",
    step_preview: "Vista Previa",
    personal_info: "Información Personal",
    full_name: "Nombre Completo",
    professional_title: "Título Profesional",
    summary: "Resumen Profesional",
    email: "Correo Electrónico",
    phone: "Teléfono",
    linkedin: "LinkedIn",
    website: "Sitio Web/Portafolio",
    work_experience: "Experiencia Laboral",
    company_name: "Nombre de la Empresa",
    job_title: "Título del Trabajo",
    start_date: "Fecha de Inicio",
    end_date: "Fecha de Finalización",
    current_job: "Trabajo Actual",
    job_description: "Descripción del Trabajo",
    add_experience: "+ Agregar Experiencia",
    education: "Educación",
    school_name: "Escuela/Universidad",
    degree: "Título",
    education_description: "Descripción",
    add_education: "+ Agregar Educación",
    skills_languages: "Habilidades e Idiomas",
    skills: "Habilidades",
    skills_placeholder: "Escriba una habilidad y presione Enter",
    languages_spoken: "Idiomas Hablados",
    select_proficiency: "Seleccionar Competencia",
    beginner: "Principiante",
    intermediate: "Intermedio",
    advanced: "Avanzado",
    native: "Nativo",
    add_language: "+ Agregar Idioma",
    certifications: "Certificaciones (Opcional)",
    preview_generate: "Vista Previa y Generar",
    choose_template: "Elegir Plantilla",
    modern_template: "Moderno",
    classic_template: "Clásico",
    minimal_template: "Minimalista",
    previous: "Anterior",
    next: "Siguiente",
    generate_pdf: "Generar PDF",
    remove: "Eliminar",
    fill_required_fields: "Por favor complete todos los campos obligatorios"
  },
  fr: {
    app_title: "Générateur de CV Intelligent",
    step_personal: "Personnel",
    step_experience: "Expérience",
    step_education: "Éducation",
    step_skills: "Compétences",
    step_preview: "Aperçu",
    personal_info: "Informations Personnelles",
    full_name: "Nom Complet",
    professional_title: "Titre Professionnel",
    summary: "Résumé Professionnel",
    email: "E-mail",
    phone: "Téléphone",
    linkedin: "LinkedIn",
    website: "Site Web/Portfolio",
    work_experience: "Expérience Professionnelle",
    company_name: "Nom de l'Entreprise",
    job_title: "Titre du Poste",
    start_date: "Date de Début",
    end_date: "Date de Fin",
    current_job: "Emploi Actuel",
    job_description: "Description du Poste",
    add_experience: "+ Ajouter une Expérience",
    education: "Éducation",
    school_name: "École/Université",
    degree: "Diplôme",
    education_description: "Description",
    add_education: "+ Ajouter une Éducation",
    skills_languages: "Compétences et Langues",
    skills: "Compétences",
    skills_placeholder: "Tapez une compétence et appuyez sur Entrée",
    languages_spoken: "Langues Parlées",
    select_proficiency: "Sélectionner la Maîtrise",
    beginner: "Débutant",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    native: "Natif",
    add_language: "+ Ajouter une Langue",
    certifications: "Certifications (Optionnel)",
    preview_generate: "Aperçu et Génération",
    choose_template: "Choisir un Modèle",
    modern_template: "Moderne",
    classic_template: "Classique",
    minimal_template: "Minimaliste",
    previous: "Précédent",
    next: "Suivant",
    generate_pdf: "Générer PDF",
    remove: "Supprimer",
    fill_required_fields: "Veuillez remplir tous les champs obligatoires"
  },
  ru: {
    app_title: "Умный Конструктор Резюме",
    step_personal: "Личное",
    step_experience: "Опыт",
    step_education: "Образование",
    step_skills: "Навыки",
    step_preview: "Предпросмотр",
    personal_info: "Личная Информация",
    full_name: "Полное Имя",
    professional_title: "Профессиональное Звание",
    summary: "Профессиональное Резюме",
    email: "Электронная Почта",
    phone: "Телефон",
    linkedin: "LinkedIn",
    website: "Веб-сайт/Портфолио",
    work_experience: "Опыт Работы",
    company_name: "Название Компании",
    job_title: "Должность",
    start_date: "Дата Начала",
    end_date: "Дата Окончания",
    current_job: "Текущая Работа",
    job_description: "Описание Работы",
    add_experience: "+ Добавить Опыт",
    education: "Образование",
    school_name: "Школа/Университет",
    degree: "Степень",
    education_description: "Описание",
    add_education: "+ Добавить Образование",
    skills_languages: "Навыки и Языки",
    skills: "Навыки",
    skills_placeholder: "Введите навык и нажмите Enter",
    languages_spoken: "Говорящие Языки",
    select_proficiency: "Выберите Уровень",
    beginner: "Начинающий",
    intermediate: "Средний",
    advanced: "Продвинутый",
    native: "Родной",
    add_language: "+ Добавить Язык",
    certifications: "Сертификации (Необязательно)",
    preview_generate: "Предпросмотр и Генерация",
    choose_template: "Выберите Шаблон",
    modern_template: "Современный",
    classic_template: "Классический",
    minimal_template: "Минималистичный",
    previous: "Предыдущий",
    next: "Следующий",
    generate_pdf: "Создать PDF",
    remove: "Удалить",
    fill_required_fields: "Пожалуйста, заполните все обязательные поля"
  }
};

export const useLanguage = () => {
  const [currentLanguage, setCurrentLanguage] = useState<keyof typeof translations>('en');

  useEffect(() => {
    const saved = localStorage.getItem('resumeBuilderLanguage');
    const browserLang = navigator.language.toLowerCase();
    
    if (saved && saved in translations) {
      setCurrentLanguage(saved as keyof typeof translations);
    } else if (browserLang === 'pt-br' || browserLang.startsWith('pt')) {
      setCurrentLanguage('pt-br');
    } else if (browserLang.startsWith('es')) {
      setCurrentLanguage('es');
    } else if (browserLang.startsWith('fr')) {
      setCurrentLanguage('fr');
    } else if (browserLang.startsWith('ru')) {
      setCurrentLanguage('ru');
    }
  }, []);

  const setLanguage = (lang: keyof typeof translations) => {
    setCurrentLanguage(lang);
    localStorage.setItem('resumeBuilderLanguage', lang);
  };

  return {
    currentLanguage,
    setLanguage,
    translations: translations[currentLanguage]
  };
};
